### ISSUE TITLE
分工合作

### ISSUE THREAD

**Issue by ghost** [OIgat-dev/OI-Helper#1]
RT，四~~五~~个部分：`抓取API`、`Web官网`、`前端（VS Code WebView一类）`、`后端（百科维护、OI大佬的模板、OJ交互……）`~~以及`吉祥物`~~

Issues留言自己选

**Comment by code004Accepted** [comment]
吉祥物

**Comment by zhaowenrui2020** [comment]
web

**Comment by lizihengcz** [comment]
web

**Comment by zhaowenrui2020** [comment]
前端

**Comment by zhaowenrui2020** [comment]
最后敲定：
liziheng 前端
chuangzhi API
zhaowenrui web官网
yemaster 后端
code004Accepted 吉祥物
